checks:
    php:
        code_rating: true
        duplication: true
build_failure_conditions:
    - 'project.metric_change("scrutinizer.quality", < -0.10)'
    - 'elements.rating(<= C).exists'               # No classes/methods with a rating of D or worse
    - 'issues.label("coding-style").exists'        # No coding style issues allowed
    - 'issues.severity(>= MAJOR).exists'           # New major or higher severity issues
    - 'project.metric("scrutinizer.quality", < 9)' # Code Quality Rating drops below 9
    - 'project.metric("scrutinizer.test_coverage", < 0.90)' # Code Coverage drops below 90%
    - 'project.metric_change("scrutinizer.test_coverage", < -0.05)'
    - 'patches.label("Doc Comments").exists'       # No doc comments patches allowed
    - 'patches.label("Spacing").exists'            # No spacing patches allowed
build:
    cache:
        directories:
            - ~/.composer
            - vendor

    dependencies:
        override:
            - composer build-ci

    environment:
        mysql: false
        postgresql: false
        elasticsearch: false
        redis: false

    tests:
        override:
            - composer cs
            -
                command: composer coverage-clover
                idle_timeout: 1200
                coverage:
                    file: 'build/coverage/clover.xml'
                    format: 'php-clover'

            - composer behat

tools:
    php_analyzer:
        enabled: true
        config:
            checkstyle:
                enabled: true
                naming:
                    isser_method_name: ^.*$
                    utility_class_name: ^.*$
            doc_comment_fixes:
                enabled: false
            reflection_fixes:
                enabled: false
            use_statement_fixes:
                enabled: false
            simplify_boolean_return:
                enabled: true
    external_code_coverage: false
    php_code_coverage: false
    php_changetracking: true
    php_cpd: true
    php_cs_fixer: false
    php_mess_detector: true
    php_pdepend: true
    sensiolabs_security_checker: true

filter:
    paths:
        - src/*

coding_style:
    php:
        spaces:
            before_parentheses:
                closure_definition: true
            around_operators:
                concatenation: false
