language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'

sudo: false
dist: trusty

matrix:
  fast_finish: true

addons:
  apt:
    packages:
    - libxml2

install:
  - composer build-ci

script:
  - composer test

cache:
  directories:
    - $HOME/.composer
